<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tax_receipt</name>
   <tag></tag>
   <elementGuidId>0ef3befc-33ff-4365-970b-13e15f66c26e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='tax_receipt'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f8f8d71-87c7-4f53-97e4-b85f9a764f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>90be9f6b-46db-4be5-8160-61721de26d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_receipt</value>
      <webElementGuid>29ff9d62-cdfb-460b-b2ee-f7f6e361f4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ที่อยู่อื่นๆ</value>
      <webElementGuid>1fdf06c6-5110-483b-b1e1-97419456b33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(this.checked){this.form.receipt_name.disabled=false;this.form.receipt_tax_id.disabled=false;this.form.receipt_branch.disabled=false;this.form.receipt_address.disabled=false;this.form.receipt_moo.disabled=false;this.form.receipt_alley.disabled=false;this.form.receipt_road.disabled=false;this.form.receipt_subdistrict.disabled=false;this.form.receipt_district.disabled=false;this.form.receipt_province.disabled=false;this.form.receipt_postcode.disabled=false;this.form.receipt_tel.disabled=false;}</value>
      <webElementGuid>96792dd7-d0b1-493b-a84e-717473cd2cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-light&quot;]/body[1]/section[@class=&quot;signup-area ptb-100&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;signup-form&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/input[2]</value>
      <webElementGuid>33dfbaae-1fa5-49b7-a56b-3d2dc6263234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='tax_receipt'])[2]</value>
      <webElementGuid>de8ee603-a1f0-4380-84fd-4b279336e851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input[2]</value>
      <webElementGuid>a22c3671-d3d2-4a15-9b27-6f3737494203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'tax_receipt']</value>
      <webElementGuid>b8ca1a4b-0619-457a-a721-d90e774052b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
